// Generated by CoffeeScript 1.6.2
(function() {
  var cycle, delay_timer, draw, fonts, i, key, loadrom, memory, opcodes, pc, rom, screen, sound_timer, stack, t, v, val, _i, _j, _len, _ref;

  opcodes = new Uint16Array();

  memory = new Uint8Array(4096);

  v = new Uint8Array(16);

  i = 0;

  sound_timer = 0;

  delay_timer = 0;

  pc = 0x200;

  stack = [];

  screen = [];

  key = 0;

  fonts = [0xF0, 0x90, 0x90, 0x90, 0xF0, 0x20, 0x60, 0x20, 0x20, 0x70, 0xF0, 0x10, 0xF0, 0x80, 0xF0, 0xF0, 0x10, 0xF0, 0x10, 0xF0, 0x90, 0x90, 0xF0, 0x10, 0x10, 0xF0, 0x80, 0xF0, 0x10, 0xF0, 0xF0, 0x80, 0xF0, 0x90, 0xF0, 0xF0, 0x10, 0x20, 0x40, 0x40, 0xF0, 0x90, 0xF0, 0x90, 0xF0, 0xF0, 0x90, 0xF0, 0x10, 0xF0, 0xF0, 0x90, 0xF0, 0x90, 0x90, 0xE0, 0x90, 0xE0, 0x90, 0xE0, 0xF0, 0x80, 0x80, 0x80, 0xF0, 0xE0, 0x90, 0x90, 0x90, 0xE0, 0xF0, 0x80, 0xF0, 0x80, 0xF0, 0xF0, 0x80, 0xF0, 0x80, 0x80];

  rom = "6e0565006b066a00a30cdab17a043a4012087b023b1212066c206d1fa310dcd122f660006100a312d0117008a30ed0116040f015f00730001234c60f671e680169ffa30ed671a310dcd16004e0a17cfe6006e0a17c02603f8c02dcd1a30ed67186848794603f8602611f8712471f12ac46006801463f68ff47006901d6713f0112aa471f12aa600580753f0012aa6001f018806061fc8012a30cd07160fe890322f6750122f6456012de124669ff806080c53f0112ca610280153f0112e080153f0112ee80153f0112e86020f018a30e7eff80e080046100d0113e00123012de78ff48fe68ff12ee7801480268016004f01869ff1270a314f533f265f12963376400d3457305f229d34500eee0008000fc00aa0000000000";

  for (t = _i = 0, _ref = rom.length / 2; 0 <= _ref ? _i <= _ref : _i >= _ref; t = 0 <= _ref ? ++_i : --_i) {
    memory[512 + t] = parseInt(rom.slice(t, t + 2), 16);
  }

  for (i = _j = 0, _len = fonts.length; _j < _len; i = ++_j) {
    val = fonts[i];
    memory[i] = fonts[i];
  }

  console.log(memory);

  loadrom = function() {};

  cycle = function() {};

  draw = function() {};

}).call(this);
